insert into public.content_entity_types (
  code,
  label,
  family,
  description,
  public_route_base,
  source_table,
  supports_import,
  supports_manual_create,
  supports_editorial_blocks,
  sort_order,
  field_schema
)
values
  (
    'stock',
    'Stocks / shares',
    'market',
    'Canonical equity pages with verified identifiers, editorial blocks, and workflow-safe publishing.',
    '/stocks',
    'instruments',
    true,
    true,
    true,
    10,
    '{"requiredIdentifiers":["canonical_slug","canonical_symbol","name"],"trustedMatchFields":["canonical_symbol","canonical_slug","exchange"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'mutual_fund',
    'Mutual funds',
    'market',
    'Fund detail pages with verified AMFI/AMC identifiers and editorial overlays.',
    '/mutual-funds',
    'mutual_funds',
    true,
    true,
    true,
    20,
    '{"requiredIdentifiers":["canonical_slug","fund_name","category"],"trustedMatchFields":["isin","amfi_code","canonical_slug"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'etf',
    'ETFs',
    'market',
    'ETF product pages governed through the same structured CMS workflow as funds and stocks.',
    '/etfs',
    'asset_registry_entries',
    true,
    true,
    true,
    30,
    '{"requiredIdentifiers":["canonical_slug","name"],"trustedMatchFields":["isin","symbol","canonical_slug"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'ipo',
    'IPOs',
    'market',
    'IPO lifecycle records with issue-stage workflow and archive-safe publishing.',
    '/ipo',
    'ipos',
    true,
    true,
    true,
    40,
    '{"requiredIdentifiers":["canonical_slug","company_name","status"],"trustedMatchFields":["canonical_slug","company_name"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'sif',
    'SIF',
    'wealth',
    'Structured investment fund product pages with operator review and publish control.',
    '/sif',
    'asset_registry_entries',
    true,
    true,
    true,
    50,
    '{"requiredIdentifiers":["canonical_slug","name"],"trustedMatchFields":["isin","manager_name","canonical_slug"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'aif',
    'AIF',
    'wealth',
    'Alternative investment fund pages with verified registry matching and gated publishing.',
    '/aif',
    'asset_registry_entries',
    true,
    true,
    true,
    60,
    '{"requiredIdentifiers":["canonical_slug","name"],"trustedMatchFields":["manager_name","scheme_code","canonical_slug"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'pms',
    'PMS',
    'wealth',
    'Portfolio management service pages with manual editorial review and publish gating.',
    '/pms',
    'asset_registry_entries',
    true,
    true,
    true,
    70,
    '{"requiredIdentifiers":["canonical_slug","name"],"trustedMatchFields":["manager_name","canonical_slug"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'course',
    'Courses',
    'education',
    'Structured education catalog pages with syllabus, modules, and publish workflow.',
    '/courses',
    'asset_registry_entries',
    true,
    true,
    true,
    80,
    '{"requiredIdentifiers":["canonical_slug","title"],"trustedMatchFields":["canonical_slug","title"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'webinar',
    'Webinars',
    'education',
    'Live and replay webinar pages with attendance, replay, and archive workflow states.',
    '/webinars',
    'asset_registry_entries',
    true,
    true,
    true,
    90,
    '{"requiredIdentifiers":["canonical_slug","title"],"trustedMatchFields":["canonical_slug","event_date","title"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'newsletter',
    'Newsletters',
    'publishing',
    'Newsletter issues and archive pages with editorial workflow and archive safety.',
    '/newsletter',
    'asset_registry_entries',
    true,
    true,
    true,
    100,
    '{"requiredIdentifiers":["canonical_slug","title"],"trustedMatchFields":["canonical_slug","issue_date","title"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'research_article',
    'Research / articles',
    'publishing',
    'Editorial research, articles, and explainers managed through review-first workflow.',
    '/learn',
    'asset_registry_entries',
    true,
    true,
    true,
    110,
    '{"requiredIdentifiers":["canonical_slug","title"],"trustedMatchFields":["canonical_slug","title"],"publicRule":"published_and_verified_only"}'::jsonb
  ),
  (
    'generic_content',
    'Future categories',
    'publishing',
    'Reusable content container for future operator-managed categories without schema rewrites.',
    null,
    null,
    true,
    true,
    true,
    999,
    '{"requiredIdentifiers":["canonical_slug","title"],"trustedMatchFields":["canonical_slug","title"],"publicRule":"published_and_verified_only"}'::jsonb
  )
on conflict (code) do update
set
  label = excluded.label,
  family = excluded.family,
  description = excluded.description,
  public_route_base = excluded.public_route_base,
  source_table = excluded.source_table,
  supports_import = excluded.supports_import,
  supports_manual_create = excluded.supports_manual_create,
  supports_editorial_blocks = excluded.supports_editorial_blocks,
  sort_order = excluded.sort_order,
  field_schema = excluded.field_schema;
