export type AdminHomeCard = {
  title: string;
  href: string;
  summary: string;
  status: "Live" | "In progress";
};

export const adminHomeCards: AdminHomeCard[] = [
  {
    title: "Content overview",
    href: "/admin/content",
    summary: "High-level view of tracked assets, coverage scores, pipeline urgency, and lifecycle readiness.",
    status: "Live",
  },
  {
    title: "Launch control",
    href: "/admin/launch-control",
    summary: "Deadline-focused view of what is coded, what is blocked, and what still needs external setup or business input.",
    status: "Live",
  },
  {
    title: "Launch config console",
    href: "/admin/launch-config-console",
    summary: "Paste Supabase, provider, billing, support, and admin-access values visually from one backend setup page instead of editing code.",
    status: "Live",
  },
  {
    title: "System status",
    href: "/admin/system-status",
    summary: "Environment-level readiness view for Supabase, auth, payments, and other launch prerequisites.",
    status: "Live",
  },
  {
    title: "Setup playbook",
    href: "/admin/setup-playbook",
    summary: "Step-by-step activation order for Supabase, auth providers, migrations, seeds, and launch verification.",
    status: "Live",
  },
  {
    title: "DB activation",
    href: "/admin/db-activation",
    summary: "Migration and seed rollout map for bringing the real backend up to the current product surface.",
    status: "Live",
  },
  {
    title: "Content rollout",
    href: "/admin/content-rollout",
    summary: "Map each public route family to its current data mode so fallback content can be replaced deliberately.",
    status: "Live",
  },
  {
    title: "API access",
    href: "/admin/api-access",
    summary: "Track which external accounts, approvals, and credentials should be collected in parallel during Phase 2.",
    status: "Live",
  },
  {
    title: "Deployment readiness",
    href: "/admin/deployment-readiness",
    summary: "Track Vercel env coverage, auth activation, email delivery, and live-go-live blockers.",
    status: "Live",
  },
  {
    title: "Communication readiness",
    href: "/admin/communication-readiness",
    summary: "Track support email, transactional email delivery, and alert-channel launch readiness.",
    status: "Live",
  },
  {
    title: "Auth activation",
    href: "/admin/auth-activation",
    summary: "Track Google login, email-link auth, callback configuration, and end-to-end auth activation work.",
    status: "Live",
  },
  {
    title: "Payment readiness",
    href: "/admin/payment-readiness",
    summary: "Track Razorpay setup, webhook readiness, billing workspace rollout, and plan-to-entitlement activation.",
    status: "Live",
  },
  {
    title: "Subscription matrix",
    href: "/admin/subscription-matrix",
    summary: "Map Starter, Pro, and Elite features so billing, entitlements, and future gating align before launch.",
    status: "Live",
  },
  {
    title: "Payment events",
    href: "/admin/payment-events",
    summary: "Review webhook event handling, billing-state transitions, and the operational meaning of subscription events.",
    status: "Live",
  },
  {
    title: "Billing ledger",
    href: "/admin/billing-ledger",
    summary: "Review subscription health, invoice continuity, renewal risk, and support follow-up from one billing operations view.",
    status: "Live",
  },
  {
    title: "Entitlements",
    href: "/admin/entitlements",
    summary: "Review access-level changes tied to billing events, support overrides, and future feature gating decisions.",
    status: "Live",
  },
  {
    title: "Platform architecture",
    href: "/admin/platform-architecture",
    summary: "Review the scale-ready CMS, SQL, lifecycle, and plugin-like module model for thousands of public pages.",
    status: "Live",
  },
  {
    title: "Module catalog",
    href: "/admin/module-catalog",
    summary: "Review installable route-family contracts so future domains behave like modules instead of custom one-off builds.",
    status: "Live",
  },
  {
    title: "Content models",
    href: "/admin/content-models",
    summary: "Track the first-class entities, workflows, and SQL structures needed for a WordPress-like CMS at fintech scale.",
    status: "Live",
  },
  {
    title: "Asset registry",
    href: "/admin/asset-registry",
    summary: "Review canonical asset ownership, alias continuity, and lifecycle-aware route mapping before scale creates duplicate records.",
    status: "Live",
  },
  {
    title: "Field dictionary",
    href: "/admin/field-dictionary",
    summary: "Review source-backed fields, editorial fields, lifecycle enums, and validation mindset before the CMS becomes hard to change.",
    status: "Live",
  },
  {
    title: "Field packs",
    href: "/admin/field-packs",
    summary: "Review reusable schema kits so new families can inherit validated field bundles instead of re-defining core structures.",
    status: "Live",
  },
  {
    title: "Operator controls",
    href: "/admin/operator-controls",
    summary: "Review how modules, behavior settings, alert visibility, and rollout modes should eventually become admin-controlled.",
    status: "Live",
  },
  {
    title: "Data lineage",
    href: "/admin/data-lineage",
    summary: "Review source traceability, editorial history, derived outputs, and user-impact audit memory before scale makes them opaque.",
    status: "Live",
  },
  {
    title: "Delivery layers",
    href: "/admin/delivery-layers",
    summary: "Review how canonical data, editorial records, derived intelligence, and public delivery artifacts stay separated.",
    status: "Live",
  },
  {
    title: "Relationships",
    href: "/admin/relationships",
    summary: "Review taxonomy and graph foundations for clusters, related pages, compare flows, and lifecycle linking.",
    status: "Live",
  },
  {
    title: "Editorial workflows",
    href: "/admin/editorial-workflows",
    summary: "Review assignment, review, and publish-queue state for manual blocks, announcements, and document operations.",
    status: "Live",
  },
  {
    title: "Publishing calendar",
    href: "/admin/publishing-calendar",
    summary: "Review scheduled release windows for stock, IPO, fund, and learning updates before the CMS goes fully live.",
    status: "Live",
  },
  {
    title: "Announcements",
    href: "/admin/announcements",
    summary: "Review manual company updates, IPO notes, and commentary records as their own editorial operating surface.",
    status: "Live",
  },
  {
    title: "Lifecycle operations",
    href: "/admin/lifecycle",
    summary: "Review IPO-to-stock transitions, archive continuity, and asset-state change planning across route families.",
    status: "Live",
  },
  {
    title: "Source jobs",
    href: "/admin/source-jobs",
    summary: "Review adapter planning, ingest cadence, and blocked feed visibility before real official-source jobs go live.",
    status: "Live",
  },
  {
    title: "Market data ops",
    href: "/admin/market-data",
    summary: "Review latency promises, cache strategy, and which surfaces are safe to activate now versus those that still need licensed realtime access.",
    status: "Live",
  },
  {
    title: "Market data playbook",
    href: "/admin/market-data-playbook",
    summary: "Review the exact validate, ingest, sync, and cron sequence for the first trusted stock set, Tata Motors chart payload, and tracked index activation.",
    status: "Live",
  },
  {
    title: "Market data tester",
    href: "/admin/market-data-tester",
    summary: "Load the sample payload and validate provider JSON before it reaches the verified first-rollout stock and index ingestion routes.",
    status: "Live",
  },
  {
    title: "Phase execution board",
    href: "/admin/phase-execution-board",
    summary: "Run Phases 17 to 20 from one operator surface instead of jumping separately across provider onboarding, canonical intake, subscriber readiness, and launch QA.",
    status: "Live",
  },
  {
    title: "Provider onboarding",
    href: "/admin/provider-onboarding",
    summary: "Configure the first trusted market-data provider and drive the first stock-set plus indices rollout from one operator handoff page.",
    status: "Live",
  },
  {
    title: "Demo showcase readiness",
    href: "/admin/demo-showcase-readiness",
    summary: "Keep tomorrow's walkthrough focused on the strongest stock, fund, and compare routes instead of losing demo polish inside the broader launch backlog.",
    status: "Live",
  },
  {
    title: "Canonical asset intake",
    href: "/admin/canonical-asset-intake",
    summary: "Give the team exact spreadsheet columns and first-wave targets for stocks, funds, IPOs, ETFs, PMS, AIF, and SIF coverage expansion.",
    status: "Live",
  },
  {
    title: "Search and screener truth",
    href: "/admin/search-screener-truth",
    summary: "Track the move from sample-driven search suggestions and screener rows to canonical asset-backed search and source-backed metric truth.",
    status: "Live",
  },
  {
    title: "Conversion path audit",
    href: "/admin/conversion-path-audit",
    summary: "Review the real public-to-subscriber journey from discovery to signup to account setup so launch confidence is based on an actual route sequence.",
    status: "Live",
  },
  {
    title: "Trust signoff",
    href: "/admin/trust-signoff",
    summary: "Review privacy, terms, support credibility, and public-promise discipline before broader promotion turns trust copy into a hard commitment.",
    status: "Live",
  },
  {
    title: "Launch commitments",
    href: "/admin/launch-commitments",
    summary: "Review the final auth, payment, support, live-data, and launch-promise blockers together so Phase 22 stays concrete and measurable.",
    status: "Live",
  },
  {
    title: "Launch day console",
    href: "/admin/launch-day-console",
    summary: "See the top blockers across provider activation, subscriber truth, conversion confidence, trust, QA, and broad-public commitments in one operator view.",
    status: "Live",
  },
  {
    title: "External activation board",
    href: "/admin/external-activation-board",
    summary: "Keep the remaining non-code setup work in one place so credentials, redirects, support delivery, and broad-public commitments are easier to execute.",
    status: "Live",
  },
  {
    title: "Launch posture board",
    href: "/admin/launch-posture-board",
    summary: "Review launch mode, public scope, and the remaining posture blockers together so the public-facing release stance is easier to decide.",
    status: "Live",
  },
  {
    title: "Release gate board",
    href: "/admin/release-gate-board",
    summary: "Review scorecard, execution queue, public posture, and preflight discipline together from one final release view.",
    status: "Live",
  },
  {
    title: "Launch blocker ledger",
    href: "/admin/launch-blocker-ledger",
    summary: "See the remaining unresolved launch items in one ledger so the final blockers are easier to assign and clear.",
    status: "Live",
  },
  {
    title: "Launch owner inbox",
    href: "/admin/launch-owner-inbox",
    summary: "Turn the remaining blockers and pending approvals into owner-specific inbox lanes so the last Phase 22 handoffs are easier to close.",
    status: "Live",
  },
  {
    title: "Launch signoff packet",
    href: "/admin/launch-signoff-packet",
    summary: "Compress blockers, owner lanes, commitments, and top actions into one final launch brief before the public decision is made.",
    status: "Live",
  },
  {
    title: "Launch evidence board",
    href: "/admin/launch-evidence-board",
    summary: "Keep the final decision grounded in one proof layer across decision mode, approvals, blocked checks, and top launch actions.",
    status: "Live",
  },
  {
    title: "External prerequisites",
    href: "/admin/external-prerequisites",
    summary: "Keep the remaining off-repo auth, payments, support, provider, and signoff tasks explicit after the Phase 22 build-side layer is complete.",
    status: "Live",
  },
  {
    title: "Public launch backlog",
    href: "/admin/public-launch-backlog",
    summary: "Track the real post-Phase-16 work still pending before a broad public signup push: live data, coverage scale, plan truth, support, and launch QA.",
    status: "Live",
  },
  {
    title: "Subscriber launch readiness",
    href: "/admin/subscriber-launch-readiness",
    summary: "Review plan gating, billing activation, support delivery, and conversion-path truth before subscriber growth moves beyond generous beta mode.",
    status: "Live",
  },
  {
    title: "Mobile QA matrix",
    href: "/admin/mobile-qa-matrix",
    summary: "Track the compact-screen pass across discovery, search, charts, auth, and subscriber workflows before broad public promotion.",
    status: "Live",
  },
  {
    title: "Public launch QA",
    href: "/admin/public-launch-qa",
    summary: "Review mobile quality, smoke tests, incident drills, launch messaging, and the final broad-public go / no-go workflow from one page.",
    status: "Live",
  },
  {
    title: "Knowledge ops",
    href: "/admin/knowledge-ops",
    summary: "Review how editorial blocks, documents, announcements, relationships, and snapshots should ground search and future AI features.",
    status: "Live",
  },
  {
    title: "CMS operations",
    href: "/admin/cms",
    summary: "Structured page blueprints, block implementation status, and the long-term editing model for your team.",
    status: "Live",
  },
  {
    title: "Block editor",
    href: "/admin/block-editor",
    summary: "Review the real block-level editing flow so staff can update one structured section at a time instead of editing raw page payloads.",
    status: "Live",
  },
  {
    title: "Rollback center",
    href: "/admin/rollback-center",
    summary: "Review how editorial and override changes should be reversed safely without losing audit history or source lineage.",
    status: "Live",
  },
  {
    title: "AI operations",
    href: "/admin/ai-ops",
    summary: "Formula-first AI control, optional live model usage, smart search planning, alert summarization, and engagement workflow design.",
    status: "Live",
  },
  {
    title: "Document library",
    href: "/admin/documents",
    summary: "Track filings, prospectuses, annual reports, factsheets, and reference assets with owner and status.",
    status: "Live",
  },
  {
    title: "Override control",
    href: "/admin/overrides",
    summary: "Manage temporary source patches, review dates, severity, and rollback-safe operational decisions.",
    status: "Live",
  },
  {
    title: "Revision log",
    href: "/admin/revisions",
    summary: "Review who changed what, when they changed it, and why.",
    status: "Live",
  },
  {
    title: "Source registry",
    href: "/admin/sources",
    summary: "Internal source-trust layer for official data, cadence, and fallback behavior.",
    status: "Live",
  },
  {
    title: "Index operations",
    href: "/admin/indexes",
    summary: "Operational view of the four-index tracker rollout and future snapshot/refresh logic.",
    status: "Live",
  },
  {
    title: "Wealth products",
    href: "/admin/wealth-products",
    summary: "Review ETF, PMS, AIF, and SIF expansion through the same CMS, registry, lifecycle, and investor-tool system.",
    status: "Live",
  },
  {
    title: "Creator studio",
    href: "/admin/creator-studio",
    summary: "Review video embeds, course media, webinar replay flow, and newsletter-ready creator publishing operations.",
    status: "Live",
  },
  {
    title: "Media library",
    href: "/admin/media-library",
    summary: "Track reusable creator assets so webinars, courses, learn pages, and campaigns can reuse one media system.",
    status: "Live",
  },
  {
    title: "Distribution ops",
    href: "/admin/distribution-ops",
    summary: "Review campaign loops, repurposing paths, and owned-distribution strategy across newsletters, alerts, and content surfaces.",
    status: "Live",
  },
  {
    title: "AI guardrails",
    href: "/admin/ai-guardrails",
    summary: "Review grounded outputs, human-review requirements, and model-on or model-off governance before AI becomes a default feature.",
    status: "Live",
  },
  {
    title: "Integration marketplace",
    href: "/admin/integration-marketplace",
    summary: "Review replaceable provider classes so payments, alerts, AI, storage, and broker integrations stay modular.",
    status: "Live",
  },
  {
    title: "Module installer",
    href: "/admin/module-installer",
    summary: "Review which route-family kits are ready to clone and which still need structural work before one-click expansion is realistic.",
    status: "Live",
  },
  {
    title: "Provider configs",
    href: "/admin/provider-configs",
    summary: "Review switchable provider profiles so env keys, callbacks, and rollout rules stay outside product logic.",
    status: "Live",
  },
  {
    title: "Reliability ops",
    href: "/admin/reliability-ops",
    summary: "Review release QA, observability, recovery planning, and production confidence gaps before scale makes them expensive.",
    status: "Live",
  },
  {
    title: "Observability",
    href: "/admin/observability",
    summary: "Review runtime, source, billing, and trust-signal visibility so failures show up before users are forced to report them.",
    status: "Live",
  },
  {
    title: "Recovery readiness",
    href: "/admin/recovery-readiness",
    summary: "Review rollback plans for content, providers, billing, and performance so operator mistakes and outages stay recoverable.",
    status: "Live",
  },
  {
    title: "Cache discipline",
    href: "/admin/cache-discipline",
    summary: "Review refresh rules, invalidation paths, and CMS revalidation before cached and near-live routes drift apart.",
    status: "Live",
  },
  {
    title: "Traffic health",
    href: "/admin/traffic-health",
    summary: "Review crawl integrity, schema quality, and route health so traffic regressions are visible before they compound.",
    status: "Live",
  },
  {
    title: "Incident response",
    href: "/admin/incident-response",
    summary: "Review runtime, source, revenue, and trust incident lanes so major failures can be contained deliberately.",
    status: "Live",
  },
  {
    title: "Performance QA",
    href: "/admin/performance-qa",
    summary: "Review public quality, discovery integrity, and release signoff discipline so launch confidence is based on more than a successful build.",
    status: "Live",
  },
  {
    title: "CRM ops",
    href: "/admin/crm-ops",
    summary: "Review lifecycle segmentation, lead scoring, and subscriber recovery planning as a real operating system instead of a future note.",
    status: "Live",
  },
  {
    title: "Campaign engine",
    href: "/admin/campaign-engine",
    summary: "Review channel families, event-driven playbooks, and consent-aware automation before growth systems are switched on.",
    status: "Live",
  },
  {
    title: "Support ops",
    href: "/admin/support-ops",
    summary: "Review help-center structure, issue triage, and subscriber-success planning before support becomes reactive and messy.",
    status: "Live",
  },
  {
    title: "Portfolio exceptions",
    href: "/admin/portfolio-exceptions",
    summary: "Review CSV mismatch handling, broker conflicts, and re-verification workflows so portfolio trust scales cleanly.",
    status: "Live",
  },
  {
    title: "Module presets",
    href: "/admin/module-presets",
    summary: "Review reusable preset bundles so future route families can launch from known patterns rather than from scratch.",
    status: "Live",
  },
  {
    title: "Lifecycle campaigns",
    href: "/admin/lifecycle-campaigns",
    summary: "Review onboarding, retention, upgrade, churn-recovery, and trust-repair journeys as one structured lifecycle layer.",
    status: "Live",
  },
  {
    title: "Provider switchboard",
    href: "/admin/provider-switchboard",
    summary: "Review primary providers, fallback paths, and rollback-safe switching rules before vendor changes become risky.",
    status: "Live",
  },
  {
    title: "Provider fallbacks",
    href: "/admin/provider-fallbacks",
    summary: "Review backup paths, rollback profiles, and resilience rules so provider outages do not silently break product trust.",
    status: "Live",
  },
  {
    title: "Provider adapters",
    href: "/admin/provider-adapters",
    summary: "Review normalized adapter contracts so providers can be swapped without rewriting product logic or rollout controls.",
    status: "Live",
  },
  {
    title: "Provider rollouts",
    href: "/admin/provider-rollouts",
    summary: "Review staged promotion, health checks, and rollback windows so provider changes become safer operations.",
    status: "Live",
  },
  {
    title: "Starter kits",
    href: "/admin/starter-kits",
    summary: "Review reusable route-family, workspace, and launch-template kits so expansion becomes repeatable instead of custom each time.",
    status: "Live",
  },
  {
    title: "Module activation",
    href: "/admin/module-activation",
    summary: "Review readiness checklists and dependency-aware enablement so modules do not appear live before they are truly ready.",
    status: "Live",
  },
  {
    title: "Segment playbooks",
    href: "/admin/segment-playbooks",
    summary: "Review lifecycle playbooks for acquisition, activation, retention, expansion, and trust recovery as one operator-ready system.",
    status: "Live",
  },
  {
    title: "Consent ops",
    href: "/admin/consent-ops",
    summary: "Review channel permissions, lifecycle eligibility, and sensitive workflow messaging rules as a dedicated backend system.",
    status: "Live",
  },
  {
    title: "Recovery journeys",
    href: "/admin/recovery-journeys",
    summary: "Review mismatch, billing, support, and trust-repair flows so failures become guided recovery journeys instead of dead ends.",
    status: "Live",
  },
  {
    title: "User success",
    href: "/admin/user-success",
    summary: "Review activation, trust repair, retention, and follow-up operations as a dedicated subscriber-success system.",
    status: "Live",
  },
  {
    title: "Journey governance",
    href: "/admin/journey-governance",
    summary: "Review support, success, campaign, consent, and recovery handoffs as one governed lifecycle system.",
    status: "Live",
  },
  {
    title: "Campaign insights",
    href: "/admin/campaign-insights",
    summary: "Review lifecycle outcomes and recovery-aware reporting so campaign work is judged by user value, not just delivery counts.",
    status: "Live",
  },
  {
    title: "Access governance",
    href: "/admin/access-governance",
    summary: "Review role boundaries, sensitive workflow protection, and future staff authorization instead of relying on signed-in-only access.",
    status: "Live",
  },
  {
    title: "Release checks",
    href: "/admin/release-checks",
    summary: "Review critical journey checks, signoff lanes, and launch discipline before production confidence depends on memory.",
    status: "Live",
  },
  {
    title: "Localization studio",
    href: "/admin/localization-studio",
    summary: "Review multilingual publishing lanes so creator and editorial media can expand beyond one-language delivery.",
    status: "Live",
  },
  {
    title: "Design system",
    href: "/admin/design-system",
    summary: "Review public-page polish and admin workflow clarity so launch quality is treated as a real refinement track.",
    status: "Live",
  },
  {
    title: "Push readiness",
    href: "/admin/push-readiness",
    summary: "Review push-safe triggers, permission-aware delivery, and mobile entry routing before app notifications go live.",
    status: "Live",
  },
  {
    title: "Cohort ops",
    href: "/admin/cohort-ops",
    summary: "Review guided program setup, creator rhythm, and subscriber progression so mentorship scales as a real operating layer.",
    status: "Live",
  },
  {
    title: "Mobile journeys",
    href: "/admin/mobile-journeys",
    summary: "Review deep-link routing, saved-state continuity, and mobile recovery entry so app journeys feel deliberate.",
    status: "Live",
  },
  {
    title: "Language rollouts",
    href: "/admin/language-rollouts",
    summary: "Review multilingual sequencing, asset versioning, and distribution-aware rollout rules before language expansion spreads.",
    status: "Live",
  },
  {
    title: "Experience audit",
    href: "/admin/experience-audit",
    summary: "Review public polish, admin clarity, and trust-focused refinement so the platform feels launch-grade, not only feature-rich.",
    status: "Live",
  },
  {
    title: "App release control",
    href: "/admin/app-release-control",
    summary: "Review app launch packaging, push/deep-link handoffs, and cross-platform signoff before native rollout moves from concept to plan.",
    status: "Live",
  },
  {
    title: "Go-live handoff",
    href: "/admin/go-live-handoff",
    summary: "Review what is truly launch-ready, what is blocked externally, and what needs shared handoff decisions before going live.",
    status: "Live",
  },
  {
    title: "External activation",
    href: "/admin/external-activation",
    summary: "Review the real provider keys, env values, source inputs, and secrets still required before the platform can launch end to end.",
    status: "Live",
  },
  {
    title: "Launch owner matrix",
    href: "/admin/launch-owner-matrix",
    summary: "Review who owns credentials, content, trust, rollout, and verification work so launch blockers never become anonymous.",
    status: "Live",
  },
  {
    title: "Launch day runbook",
    href: "/admin/launch-day-runbook",
    summary: "Review the same-day launch sequence, high-risk checkpoints, and fallback actions before traffic is deliberately invited.",
    status: "Live",
  },
  {
    title: "Launch scope",
    href: "/admin/launch-scope",
    summary: "Review what should be public, gated, hidden, or roadmap-positioned so the first release stays trustworthy.",
    status: "Live",
  },
  {
    title: "Preflight checklist",
    href: "/admin/preflight-checklist",
    summary: "Review final route checks, provider validation, rollback readiness, and owner signoff before public promotion starts.",
    status: "Live",
  },
  {
    title: "Launch mode",
    href: "/admin/launch-mode",
    summary: "Review whether the platform should currently present as internal review, launch prep, public beta, or full launch.",
    status: "Live",
  },
  {
    title: "Beta gate",
    href: "/admin/beta-gate",
    summary: "Review which surfaces are safe for a controlled public beta and which should stay restricted until trust and provider readiness improve.",
    status: "Live",
  },
  {
    title: "Launch scorecard",
    href: "/admin/launch-scorecard",
    summary: "Review a fast readiness score across envs, support setup, payments, optional AI, and current launch posture.",
    status: "Live",
  },
  {
    title: "Domain readiness",
    href: "/admin/domain-readiness",
    summary: "Review whether domain, callback expectations, sitemap base, and trust contact are aligned for real launch.",
    status: "Live",
  },
  {
    title: "Credential matrix",
    href: "/admin/credential-matrix",
    summary: "Review the exact env keys, whether they are present, and what each one powers across launch activation.",
    status: "Live",
  },
  {
    title: "Callback matrix",
    href: "/admin/callback-matrix",
    summary: "Review the exact local, production, and Supabase callback values required for auth and provider setup.",
    status: "Live",
  },
  {
    title: "Activation sequence",
    href: "/admin/activation-sequence",
    summary: "Review the exact order for env setup, auth activation, redeploy, and preflight signoff before launch moves forward.",
    status: "Live",
  },
  {
    title: "Live smoke tests",
    href: "/admin/live-smoke-tests",
    summary: "Review the exact launch-day verification flow for login, protected routes, support trust, payments, and public posture.",
    status: "Live",
  },
  {
    title: "Launch decision",
    href: "/admin/launch-decision",
    summary: "Review the highest safe launch mode the platform can claim right now based on real blockers instead of optimism.",
    status: "Live",
  },
  {
    title: "Go / no-go",
    href: "/admin/go-no-go",
    summary: "Review the single launch recommendation based on blockers, readiness, activation order, and smoke-test coverage.",
    status: "Live",
  },
  {
    title: "Launch approvals",
    href: "/admin/launch-approvals",
    summary: "Review the final owner signoff lanes so scope, engineering, support, and monetization never launch by assumption.",
    status: "Live",
  },
  {
    title: "Beta command center",
    href: "/admin/beta-command-center",
    summary: "Review whether the product is operationally ready to cross from launch prep into a controlled public beta.",
    status: "Live",
  },
  {
    title: "Beta feedback",
    href: "/admin/beta-feedback",
    summary: "Review early-user feedback lanes so trust issues, auth friction, and pricing confusion are tightened before beta expands.",
    status: "Live",
  },
  {
    title: "Beta triage",
    href: "/admin/beta-triage",
    summary: "Review severity, owner, and immediate response rules for the first wave of beta issues.",
    status: "Live",
  },
  {
    title: "Beta invite plan",
    href: "/admin/beta-invite-plan",
    summary: "Review how access should widen from inner-circle testing to broader beta without outrunning trust and support.",
    status: "Live",
  },
  {
    title: "Beta metrics",
    href: "/admin/beta-metrics",
    summary: "Review whether the beta is actually improving trust, support confidence, and product clarity before wider expansion.",
    status: "Live",
  },
  {
    title: "Beta ops runbook",
    href: "/admin/beta-ops-runbook",
    summary: "Review the daily operating rhythm for controlled beta so posture, support, feedback, and invite decisions stay disciplined.",
    status: "Live",
  },
  {
    title: "Reference parity",
    href: "/admin/reference-parity",
    summary: "Review what charts, stock pages, IPO pages, fund pages, wealth pages, and learning still need before the product feels reference-grade.",
    status: "Live",
  },
  {
    title: "Announcement readiness",
    href: "/admin/announcement-readiness",
    summary: "Review the public-beta message, trust cues, and launch-claim discipline before posting or tweeting about the platform.",
    status: "Live",
  },
  {
    title: "Learning paths",
    href: "/admin/learning-paths",
    summary: "Review beginner, trader, and wealth-builder education tracks so Phase 16 becomes a sequenced product layer instead of isolated content cards.",
    status: "Live",
  },
  {
    title: "Education library",
    href: "/admin/education-library",
    summary: "Review how courses, webinars, replay assets, bundles, and mentorship ladders connect into one real library system.",
    status: "Live",
  },
  {
    title: "Mentorship ladders",
    href: "/admin/mentorship-ladders",
    summary: "Review how courses, webinars, cohorts, community loops, and premium progression should connect into one guided learning ladder.",
    status: "Live",
  },
  {
    title: "Replay memory",
    href: "/admin/replay-memory",
    summary: "Review how webinars, newsletters, cohorts, and archive continuity should turn into durable replay chains instead of one-time assets.",
    status: "Live",
  },
  {
    title: "Asset memory",
    href: "/admin/asset-memory",
    summary: "Review how stocks, IPOs, funds, wealth products, and learning assets should preserve durable memory instead of one-time page state.",
    status: "Live",
  },
  {
    title: "Source mapping desk",
    href: "/admin/source-mapping-desk",
    summary: "Review the human handoff for canonical asset sheets, trusted source mapping, and editorial-template prep needed for scale.",
    status: "Live",
  },
  {
    title: "Source entry console",
    href: "/admin/source-entry-console",
    summary: "Use one operator view for index roster corrections, commodity history entry, and launch-critical public-route overrides.",
    status: "Live",
  },
  {
    title: "Research archive",
    href: "/admin/research-archive",
    summary: "Review results memory, IPO lifecycle history, fund commentary continuity, and the broader market-memory layer now growing in Phase 16.",
    status: "Live",
  },
];

export const adminHomeRules = [
  "This backend should stay simple enough for non-technical operators while still respecting structured data and audit rules.",
  "Manual editing, uploads, overrides, AI review, and publishing history should all connect back to one clear admin entry point.",
  "The final rename from the temporary Riddra brand should happen through shared configuration and backend-aware copy, not scattered page edits.",
];
