export const siteConfig = {
  name: "Riddra",
  description:
    "SEO-first market intelligence for Indian investors and traders, with premium tools layered on top.",
  url: "https://riddra.com",
  tagline: "Market intelligence that earns traffic and subscriptions.",
};

export const primaryNav = [
  { href: "/stocks", label: "Indian Stocks" },
  { href: "/sensex", label: "Sensex" },
  { href: "/nifty50", label: "Nifty50" },
  { href: "/banknifty", label: "BankNifty" },
  { href: "/finnifty", label: "FinNifty" },
];

export const publicMarketNav = [
  { href: "/", label: "Home" },
  ...primaryNav,
];

export const publicUtilityNav = [
  { href: "/screener", label: "Screener" },
  { href: "/courses", label: "Courses" },
  { href: "/tools", label: "Calculators" },
  { href: "/charts", label: "Charts" },
  { href: "/markets", label: "Markets" },
  { href: "/mutual-funds", label: "Mutual Funds" },
  { href: "/learn", label: "Learn" },
  { href: "/newsletter", label: "Newsletter" },
];

export const publicSecondaryNav = [
  { href: "/build-tracker", label: "Build Tracker" },
  { href: "/get-started", label: "Get Started" },
  { href: "/pricing", label: "Pricing" },
  { href: "/screener", label: "Screener" },
  { href: "/markets", label: "Markets" },
  { href: "/indices", label: "Indices" },
  { href: "/charts", label: "Charts" },
  { href: "/trader-workstation", label: "Workstation" },
  { href: "/chart-layouts", label: "Chart Layouts" },
  { href: "/option-chain", label: "Option Chain" },
  { href: "/scanner-presets", label: "Scanner Presets" },
  { href: "/index-replay", label: "Index Replay" },
  { href: "/trader-presets", label: "Trader Presets" },
  { href: "/search", label: "Search" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/alerts", label: "Alerts" },
  { href: "/tools", label: "Tools" },
  { href: "/source-readiness", label: "Source Readiness" },
  { href: "/launch-readiness", label: "Launch Readiness" },
  { href: "/learn", label: "Learn" },
  { href: "/courses", label: "Courses" },
  { href: "/webinars", label: "Webinars" },
  { href: "/newsletter", label: "Newsletter" },
  { href: "/market-copilot", label: "Market Copilot" },
  { href: "/reports", label: "Reports" },
  { href: "/reports/fii-dii", label: "FII / DII" },
  { href: "/reports/results-calendar", label: "Results" },
  { href: "/sectors", label: "Sectors" },
  { href: "/fund-categories", label: "Fund Categories" },
  { href: "/ipo", label: "IPO Hub" },
  { href: "/ipo/sme", label: "SME IPOs" },
  { href: "/mutual-funds", label: "Mutual Funds" },
  { href: "/wealth", label: "Wealth Hub" },
  { href: "/etfs", label: "ETFs" },
  { href: "/pms", label: "PMS" },
  { href: "/aif", label: "AIF" },
  { href: "/sif", label: "SIF" },
  { href: "/methodology", label: "Methodology" },
  { href: "/privacy", label: "Privacy" },
  { href: "/terms", label: "Terms" },
  { href: "/contact", label: "Contact" },
  { href: "/help", label: "Help Center" },
  { href: "/mobile-app", label: "Mobile" },
  { href: "/mentorship", label: "Mentorship" },
  { href: "/community", label: "Community" },
];

export const workspaceNav = [
  { href: "/account", label: "Account" },
  { href: "/account/setup", label: "Account Setup" },
  { href: "/account/workspace", label: "Workspace Hub" },
  { href: "/account/inbox", label: "Inbox" },
  { href: "/account/support", label: "Support" },
  { href: "/account/watchlists", label: "Watchlists" },
  { href: "/account/screens", label: "Saved Screens" },
  { href: "/account/alerts", label: "Alert Preferences" },
  { href: "/account/consents", label: "Consent Center" },
  { href: "/account/brokers", label: "Broker Connections" },
  { href: "/account/access", label: "Access Model" },
  { href: "/account/access/entitlements", label: "Entitlement Audit" },
  { href: "/account/billing", label: "Billing" },
  { href: "/account/billing/lifecycle", label: "Billing Lifecycle" },
  { href: "/account/billing/recovery", label: "Billing Recovery" },
];

export const adminNav = [
  { href: "/admin", label: "Admin" },
  { href: "/admin/launch-control", label: "Launch Control" },
  { href: "/admin/system-status", label: "System Status" },
  { href: "/admin/runtime-diagnostics", label: "Runtime Diagnostics" },
  { href: "/admin/setup-playbook", label: "Setup Playbook" },
  { href: "/admin/db-activation", label: "DB Activation" },
  { href: "/admin/content-rollout", label: "Content Rollout" },
  { href: "/admin/api-access", label: "API Access" },
  { href: "/admin/deployment-readiness", label: "Deployment Readiness" },
  { href: "/admin/communication-readiness", label: "Communication Readiness" },
  { href: "/admin/auth-activation", label: "Auth Activation" },
  { href: "/admin/payment-readiness", label: "Payment Readiness" },
  { href: "/admin/subscription-matrix", label: "Subscription Matrix" },
  { href: "/admin/payment-events", label: "Payment Events" },
  { href: "/admin/billing-ledger", label: "Billing Ledger" },
  { href: "/admin/entitlements", label: "Entitlements" },
  { href: "/admin/platform-architecture", label: "Platform Architecture" },
  { href: "/admin/module-catalog", label: "Module Catalog" },
  { href: "/admin/content-models", label: "Content Models" },
  { href: "/admin/asset-registry", label: "Asset Registry" },
  { href: "/admin/field-dictionary", label: "Field Dictionary" },
  { href: "/admin/field-packs", label: "Field Packs" },
  { href: "/admin/operator-controls", label: "Operator Controls" },
  { href: "/admin/integration-marketplace", label: "Integration Marketplace" },
  { href: "/admin/module-installer", label: "Module Installer" },
  { href: "/admin/provider-configs", label: "Provider Configs" },
  { href: "/admin/reliability-ops", label: "Reliability Ops" },
  { href: "/admin/observability", label: "Observability" },
  { href: "/admin/recovery-readiness", label: "Recovery Readiness" },
  { href: "/admin/cache-discipline", label: "Cache Discipline" },
  { href: "/admin/traffic-health", label: "Traffic Health" },
  { href: "/admin/incident-response", label: "Incident Response" },
  { href: "/admin/performance-qa", label: "Performance QA" },
  { href: "/admin/crm-ops", label: "CRM Ops" },
  { href: "/admin/campaign-engine", label: "Campaign Engine" },
  { href: "/admin/support-ops", label: "Support Ops" },
  { href: "/admin/portfolio-exceptions", label: "Portfolio Exceptions" },
  { href: "/admin/module-presets", label: "Module Presets" },
  { href: "/admin/lifecycle-campaigns", label: "Lifecycle Campaigns" },
  { href: "/admin/provider-switchboard", label: "Provider Switchboard" },
  { href: "/admin/provider-fallbacks", label: "Provider Fallbacks" },
  { href: "/admin/provider-adapters", label: "Provider Adapters" },
  { href: "/admin/provider-rollouts", label: "Provider Rollouts" },
  { href: "/admin/starter-kits", label: "Starter Kits" },
  { href: "/admin/module-activation", label: "Module Activation" },
  { href: "/admin/segment-playbooks", label: "Segment Playbooks" },
  { href: "/admin/consent-ops", label: "Consent Ops" },
  { href: "/admin/recovery-journeys", label: "Recovery Journeys" },
  { href: "/admin/user-success", label: "User Success" },
  { href: "/admin/journey-governance", label: "Journey Governance" },
  { href: "/admin/campaign-insights", label: "Campaign Insights" },
  { href: "/admin/access-governance", label: "Access Governance" },
  { href: "/admin/release-checks", label: "Release Checks" },
  { href: "/admin/localization-studio", label: "Localization Studio" },
  { href: "/admin/design-system", label: "Design System" },
  { href: "/admin/push-readiness", label: "Push Readiness" },
  { href: "/admin/cohort-ops", label: "Cohort Ops" },
  { href: "/admin/mobile-journeys", label: "Mobile Journeys" },
  { href: "/admin/language-rollouts", label: "Language Rollouts" },
  { href: "/admin/experience-audit", label: "Experience Audit" },
  { href: "/admin/app-release-control", label: "App Release Control" },
  { href: "/admin/go-live-handoff", label: "Go-Live Handoff" },
  { href: "/admin/external-activation", label: "External Activation" },
  { href: "/admin/launch-owner-matrix", label: "Launch Owner Matrix" },
  { href: "/admin/launch-day-runbook", label: "Launch Day Runbook" },
  { href: "/admin/launch-scope", label: "Launch Scope" },
  { href: "/admin/preflight-checklist", label: "Preflight Checklist" },
  { href: "/admin/launch-mode", label: "Launch Mode" },
  { href: "/admin/beta-gate", label: "Beta Gate" },
  { href: "/admin/launch-scorecard", label: "Launch Scorecard" },
  { href: "/admin/domain-readiness", label: "Domain Readiness" },
  { href: "/admin/credential-matrix", label: "Credential Matrix" },
  { href: "/admin/callback-matrix", label: "Callback Matrix" },
  { href: "/admin/activation-sequence", label: "Activation Sequence" },
  { href: "/admin/live-smoke-tests", label: "Live Smoke Tests" },
  { href: "/admin/launch-decision", label: "Launch Decision" },
  { href: "/admin/go-no-go", label: "Go / No-Go" },
  { href: "/admin/launch-approvals", label: "Launch Approvals" },
  { href: "/admin/beta-command-center", label: "Beta Command Center" },
  { href: "/admin/beta-feedback", label: "Beta Feedback" },
  { href: "/admin/beta-triage", label: "Beta Triage" },
  { href: "/admin/beta-invite-plan", label: "Beta Invite Plan" },
  { href: "/admin/beta-metrics", label: "Beta Metrics" },
  { href: "/admin/beta-ops-runbook", label: "Beta Ops Runbook" },
  { href: "/admin/reference-parity", label: "Reference Parity" },
  { href: "/admin/announcement-readiness", label: "Announcement Readiness" },
  { href: "/admin/learning-paths", label: "Learning Paths" },
  { href: "/admin/education-library", label: "Education Library" },
  { href: "/admin/mentorship-ladders", label: "Mentorship Ladders" },
  { href: "/admin/replay-memory", label: "Replay Memory" },
  { href: "/admin/asset-memory", label: "Asset Memory" },
  { href: "/admin/source-mapping-desk", label: "Source Mapping Desk" },
  { href: "/admin/source-entry-console", label: "Source Entry Console" },
  { href: "/admin/launch-config-console", label: "Launch Config Console" },
  { href: "/admin/canonical-asset-intake", label: "Canonical Asset Intake" },
  { href: "/admin/demo-showcase-readiness", label: "Demo Showcase Readiness" },
  { href: "/admin/public-launch-backlog", label: "Public Launch Backlog" },
  { href: "/admin/research-archive", label: "Research Archive" },
  { href: "/admin/data-lineage", label: "Data Lineage" },
  { href: "/admin/delivery-layers", label: "Delivery Layers" },
  { href: "/admin/relationships", label: "Relationships" },
  { href: "/admin/editorial-workflows", label: "Editorial Workflows" },
  { href: "/admin/publishing-calendar", label: "Publishing Calendar" },
  { href: "/admin/announcements", label: "Announcements" },
  { href: "/admin/lifecycle", label: "Lifecycle Ops" },
  { href: "/admin/source-jobs", label: "Source Jobs" },
  { href: "/admin/market-data", label: "Market Data Ops" },
  { href: "/admin/market-data-playbook", label: "Market Data Playbook" },
  { href: "/admin/market-data-tester", label: "Market Data Tester" },
  { href: "/admin/phase-execution-board", label: "Phase Execution Board" },
  { href: "/admin/provider-onboarding", label: "Provider Onboarding" },
  { href: "/admin/search-screener-truth", label: "Search & Screener Truth" },
  { href: "/admin/conversion-path-audit", label: "Conversion Path Audit" },
  { href: "/admin/trust-signoff", label: "Trust Signoff" },
  { href: "/admin/launch-commitments", label: "Launch Commitments" },
  { href: "/admin/launch-day-console", label: "Launch Day Console" },
  { href: "/admin/external-activation-board", label: "External Activation Board" },
  { href: "/admin/launch-posture-board", label: "Launch Posture Board" },
  { href: "/admin/release-gate-board", label: "Release Gate Board" },
  { href: "/admin/launch-blocker-ledger", label: "Launch Blocker Ledger" },
  { href: "/admin/launch-owner-inbox", label: "Launch Owner Inbox" },
  { href: "/admin/launch-signoff-packet", label: "Launch Signoff Packet" },
  { href: "/admin/launch-evidence-board", label: "Launch Evidence Board" },
  { href: "/admin/external-prerequisites", label: "External Prerequisites" },
  { href: "/admin/subscriber-launch-readiness", label: "Subscriber Launch Readiness" },
  { href: "/admin/mobile-qa-matrix", label: "Mobile QA Matrix" },
  { href: "/admin/public-launch-qa", label: "Public Launch QA" },
  { href: "/admin/knowledge-ops", label: "Knowledge Ops" },
  { href: "/admin/cms", label: "CMS Ops" },
  { href: "/admin/block-editor", label: "Block Editor" },
  { href: "/admin/rollback-center", label: "Rollback Center" },
  { href: "/admin/ai-ops", label: "AI Ops" },
  { href: "/admin/documents", label: "Documents" },
  { href: "/admin/overrides", label: "Overrides" },
  { href: "/admin/revisions", label: "Revisions" },
  { href: "/admin/indexes", label: "Index Ops" },
  { href: "/admin/wealth-products", label: "Wealth Products" },
  { href: "/admin/creator-studio", label: "Creator Studio" },
  { href: "/admin/media-library", label: "Media Library" },
  { href: "/admin/distribution-ops", label: "Distribution Ops" },
  { href: "/admin/ai-guardrails", label: "AI Guardrails" },
];

export const secondaryNav = [...publicSecondaryNav, ...workspaceNav, ...adminNav];

export const corePillars = [
  {
    title: "Traffic Engine",
    description:
      "Stock, IPO, and fund pages designed to rank, refresh often, and create a long-term SEO moat.",
  },
  {
    title: "Subscriber Value",
    description:
      "Watchlists, screeners, live dashboards, and derivatives workflows that justify recurring plans.",
  },
  {
    title: "AI Layer",
    description:
      "Formula-first intelligence with optional live AI, grounded in your own structured market data.",
  },
];

export const roadmapPhases = [
  {
    phase: "Phase 0",
    title: "Foundation",
    description:
      "Brand placeholder, app shell, auth routes, pricing, SEO route system, and content-ready layouts.",
  },
  {
    phase: "Phase 1",
    title: "Traffic Engine",
    description:
      "Stock pages, IPO hub, mutual fund pages, index trackers, schema markup, and discovery workflow.",
  },
  {
    phase: "Phase 2",
    title: "Subscriber Toolkit",
    description:
      "Screener, premium dashboards, watchlists, advanced charts, portfolio tools, plan gating, and account areas.",
  },
  {
    phase: "Phase 3",
    title: "Trader Depth",
    description:
      "Option chain, OI analytics, alerts, advanced charts, and premium workflows.",
  },
  {
    phase: "Phase 4",
    title: "Trader Workstation",
    description:
      "Chart layouts, replay, presets, scanner workflows, and trader-grade analysis surfaces.",
  },
  {
    phase: "Phase 5",
    title: "Wealth Expansion",
    description:
      "ETF, PMS, AIF, SIF, wealth utilities, and long-tail investor research surfaces.",
  },
  {
    phase: "Phase 6",
    title: "Learning and Distribution",
    description:
      "Courses, webinars, newsletters, creator studio, media workflows, and distribution operations.",
  },
  {
    phase: "Phase 7",
    title: "AI Layer",
    description:
      "Formula-first copilot features, smart search answers, AI guardrails, and optional low-cost live AI.",
  },
  {
    phase: "Phase 8",
    title: "Platform OS",
    description:
      "Module catalogs, field packs, lineage, delivery layers, and scale-ready CMS architecture.",
  },
  {
    phase: "Phase 9",
    title: "Extensibility",
    description:
      "Provider marketplace, adapters, fallbacks, switchboards, presets, and installable starter kits.",
  },
  {
    phase: "Phase 10",
    title: "Growth Ops",
    description:
      "CRM, lifecycle campaigns, consent governance, support ops, exception handling, and help center operations.",
  },
  {
    phase: "Phase 11",
    title: "Reliability",
    description:
      "Release QA, observability, RBAC, recovery, performance, and production confidence.",
  },
  {
    phase: "Phase 12",
    title: "Mobile and Experience",
    description:
      "Mobile app readiness, mentorship/community, multilingual learning, and product-polish upgrades inspired by stronger market platforms.",
  },
  {
    phase: "Phase 13",
    title: "Launch Activation",
    description:
      "Credentials, provider activation, public-scope control, launch mode, and preflight verification before any public announcement.",
  },
  {
    phase: "Phase 14",
    title: "Controlled Beta",
    description:
      "Limited public release with active monitoring, support readiness, rollback discipline, and trust-focused iteration.",
  },
  {
    phase: "Phase 15",
    title: "Public Go-Live",
    description:
      "Reference-grade charts, denser research pages, structured screeners, and broad launch confidence once the platform is truly tweet-ready.",
  },
  {
    phase: "Phase 16",
    title: "Parity and Learning",
    description:
      "Deeper education library, research archives, and evidence-led upgrades toward the strongest reference product experiences.",
  },
];

export const pricingPlans = [
  {
    name: "Starter",
    price: "Free",
    summary: "For users who want market snapshots, public stock pages, compare routes, tools, and basic account continuity without a paid commitment.",
    ctaLabel: "Start free",
    ctaHref: "/signup",
    ctaNote: "Best for first-time users evaluating the product before moving into deeper research or trading workflows.",
    features: ["Public market routes", "Basic watchlists", "Core tools", "Entry-level screener access", "Free account continuity"],
  },
  {
    name: "Pro",
    price: "₹499/mo",
    summary: "For active users who want deeper screeners, faster research workflows, smarter alerts, and stronger decision support across stocks and indices.",
    ctaLabel: "Choose Pro",
    ctaHref: "/get-started",
    ctaNote: "Best for regular traders and serious market-followers who need more than the free public layer.",
    features: [
      "Advanced screeners",
      "Saved screens and alerts",
      "Deeper chart workflows",
      "Faster compare and workflow shortcuts",
    ],
  },
  {
    name: "Elite",
    price: "₹1,499/mo",
    summary: "For power users who want the deepest research layer, priority support, faster feature access, and the strongest workspace depth.",
    ctaLabel: "Apply for Elite",
    ctaHref: "/signup",
    ctaNote: "Best for high-intent traders, researchers, and early adopters who want the fullest Riddra operating layer.",
    features: ["Everything in Pro", "Priority support", "Advanced workflow layer", "Early premium features"],
    featured: true,
  },
];
