import type { AdminEditorRecord } from "@/lib/admin-content-schema";

export type StockFieldDataSourceType =
  | "imported_time_series"
  | "manual_snapshot"
  | "editorial_content"
  | "computed"
  | "source_derived";

export type StockFieldFormat =
  | "currency"
  | "percent"
  | "number"
  | "text"
  | "textarea"
  | "date"
  | "url";

export type StockFieldEditableBy = "admin" | "editor" | "none";
export type StockFieldPriority = "critical" | "important" | "optional";
export type StockFieldSectionId =
  | "hero_identity"
  | "price_snapshot"
  | "range_coverage"
  | "r_score"
  | "chart_history"
  | "investor_details"
  | "performance"
  | "fundamentals"
  | "ownership"
  | "forecast"
  | "latest_news"
  | "faq"
  | "seo_sharing"
  | "documents_references";

export type StockInlineEditSectionId =
  | "hero_identity"
  | "price_snapshot"
  | "investor_details"
  | "fundamentals"
  | "ownership"
  | "forecast"
  | "seo_content";

export type StockFieldRegistryEntry = {
  id: string;
  sectionId: StockFieldSectionId;
  sectionLabel: string;
  frontendLabel: string;
  backendFieldKey: string;
  dataSourceType: StockFieldDataSourceType;
  expectedFormat: StockFieldFormat;
  editableBy: StockFieldEditableBy;
  importable: boolean;
  requiredPriority: StockFieldPriority;
  publicRouteSection: string;
  adminSectionKey?: string | null;
  adminFieldKey?: string | null;
  helpText?: string;
  options?: Array<{ label: string; value: string }>;
};

export type StockFieldMapRow = StockFieldRegistryEntry & {
  currentValue: string;
  missing: boolean;
  statusLabel: string;
};

export type StockInlineEditSection = {
  id: StockInlineEditSectionId;
  label: string;
  description: string;
  entryIds: string[];
  managedByImportNote?: string;
};

const yesNoOptions = [
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" },
];

const stockFieldRegistry: StockFieldRegistryEntry[] = [
  {
    id: "hero-company-name",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Company name",
    backendFieldKey: "identity.companyName",
    adminSectionKey: "identity",
    adminFieldKey: "companyName",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "critical",
    publicRouteSection: "summary",
  },
  {
    id: "hero-symbol",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Symbol",
    backendFieldKey: "identity.symbol",
    adminSectionKey: "identity",
    adminFieldKey: "symbol",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "critical",
    publicRouteSection: "summary",
  },
  {
    id: "hero-sector",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Sector",
    backendFieldKey: "identity.sector",
    adminSectionKey: "identity",
    adminFieldKey: "sector",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "hero-sector-index",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Sector comparison index",
    backendFieldKey: "identity.sectorIndexSlug",
    adminSectionKey: "identity",
    adminFieldKey: "sectorIndexSlug",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "hero-benchmark",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Benchmark",
    backendFieldKey: "identity.benchmarkSlug",
    adminSectionKey: "identity",
    adminFieldKey: "benchmarkSlug",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "hero-industry",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Industry",
    backendFieldKey: "identity.industry",
    adminSectionKey: "identity",
    adminFieldKey: "industry",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "hero-summary",
    sectionId: "hero_identity",
    sectionLabel: "Hero / identity",
    frontendLabel: "Summary",
    backendFieldKey: "frontend_fields.summary",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "summary",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "critical",
    publicRouteSection: "summary",
  },
  {
    id: "snapshot-current-price",
    sectionId: "price_snapshot",
    sectionLabel: "Price snapshot",
    frontendLabel: "Current price",
    backendFieldKey: "market_snapshot.currentPrice",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "currentPrice",
    dataSourceType: "manual_snapshot",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "critical",
    publicRouteSection: "summary",
  },
  {
    id: "snapshot-day-change",
    sectionId: "price_snapshot",
    sectionLabel: "Price snapshot",
    frontendLabel: "Day change",
    backendFieldKey: "market_snapshot.dayChange",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "dayChange",
    dataSourceType: "manual_snapshot",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "critical",
    publicRouteSection: "summary",
  },
  {
    id: "snapshot-as-of",
    sectionId: "price_snapshot",
    sectionLabel: "Price snapshot",
    frontendLabel: "Snapshot as of",
    backendFieldKey: "market_snapshot.snapshotAsOf",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "snapshotAsOf",
    dataSourceType: "manual_snapshot",
    expectedFormat: "date",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "snapshot-prev-close",
    sectionId: "price_snapshot",
    sectionLabel: "Price snapshot",
    frontendLabel: "Previous close",
    backendFieldKey: "stock_ohlcv_history.previous_close",
    dataSourceType: "imported_time_series",
    expectedFormat: "currency",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "summary",
    helpText: "Derived from the previous imported daily OHLCV row.",
  },
  {
    id: "snapshot-market-cap",
    sectionId: "price_snapshot",
    sectionLabel: "Price snapshot",
    frontendLabel: "Market cap",
    backendFieldKey: "market_snapshot.marketCap",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "marketCap",
    dataSourceType: "manual_snapshot",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "range-today-open",
    sectionId: "range_coverage",
    sectionLabel: "Today range / 52-week range",
    frontendLabel: "Today open",
    backendFieldKey: "stock_ohlcv_history.open",
    dataSourceType: "imported_time_series",
    expectedFormat: "currency",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "summary",
    helpText: "Managed by Market Data Import from daily OHLCV rows.",
  },
  {
    id: "range-today-high",
    sectionId: "range_coverage",
    sectionLabel: "Today range / 52-week range",
    frontendLabel: "Today high",
    backendFieldKey: "stock_ohlcv_history.high",
    dataSourceType: "imported_time_series",
    expectedFormat: "currency",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "summary",
    helpText: "Managed by Market Data Import from daily OHLCV rows.",
  },
  {
    id: "range-today-low",
    sectionId: "range_coverage",
    sectionLabel: "Today range / 52-week range",
    frontendLabel: "Today low",
    backendFieldKey: "stock_ohlcv_history.low",
    dataSourceType: "imported_time_series",
    expectedFormat: "currency",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "summary",
    helpText: "Managed by Market Data Import from daily OHLCV rows.",
  },
  {
    id: "range-52w-high",
    sectionId: "range_coverage",
    sectionLabel: "Today range / 52-week range",
    frontendLabel: "52-week high",
    backendFieldKey: "market_snapshot.week52High",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "week52High",
    dataSourceType: "manual_snapshot",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "range-52w-low",
    sectionId: "range_coverage",
    sectionLabel: "Today range / 52-week range",
    frontendLabel: "52-week low",
    backendFieldKey: "market_snapshot.week52Low",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "week52Low",
    dataSourceType: "manual_snapshot",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "r-score",
    sectionId: "r_score",
    sectionLabel: "R Score",
    frontendLabel: "R Score",
    backendFieldKey: "computed.rScore",
    dataSourceType: "computed",
    expectedFormat: "number",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
    helpText: "Computed from momentum, quality, ownership, and coverage signals.",
  },
  {
    id: "chart-history",
    sectionId: "chart_history",
    sectionLabel: "Chart / price history",
    frontendLabel: "Daily price candles",
    backendFieldKey: "stock_ohlcv_history",
    dataSourceType: "imported_time_series",
    expectedFormat: "text",
    editableBy: "none",
    importable: true,
    requiredPriority: "critical",
    publicRouteSection: "summary",
    helpText: "Managed only by Market Data Import. Not editable from the stock page.",
  },
  {
    id: "chart-benchmark-history",
    sectionId: "chart_history",
    sectionLabel: "Chart / price history",
    frontendLabel: "Benchmark candles",
    backendFieldKey: "benchmark_ohlcv_history",
    dataSourceType: "imported_time_series",
    expectedFormat: "text",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "summary",
    helpText: "Managed only by Market Data Import. Not editable from the stock page.",
  },
  {
    id: "investor-pe",
    sectionId: "investor_details",
    sectionLabel: "Investor details",
    frontendLabel: "P/E",
    backendFieldKey: "market_snapshot.peRatio",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "peRatio",
    dataSourceType: "manual_snapshot",
    expectedFormat: "number",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "investor-pb",
    sectionId: "investor_details",
    sectionLabel: "Investor details",
    frontendLabel: "P/B",
    backendFieldKey: "market_snapshot.pbRatio",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "pbRatio",
    dataSourceType: "manual_snapshot",
    expectedFormat: "number",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "investor-roe",
    sectionId: "investor_details",
    sectionLabel: "Investor details",
    frontendLabel: "ROE",
    backendFieldKey: "market_snapshot.roe",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "roe",
    dataSourceType: "manual_snapshot",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "investor-roce",
    sectionId: "investor_details",
    sectionLabel: "Investor details",
    frontendLabel: "ROCE",
    backendFieldKey: "market_snapshot.roce",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "roce",
    dataSourceType: "manual_snapshot",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "investor-dividend-yield",
    sectionId: "investor_details",
    sectionLabel: "Investor details",
    frontendLabel: "Dividend yield",
    backendFieldKey: "market_snapshot.dividendYield",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "dividendYield",
    dataSourceType: "manual_snapshot",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "investor-debt-equity",
    sectionId: "investor_details",
    sectionLabel: "Investor details",
    frontendLabel: "Debt / equity",
    backendFieldKey: "market_snapshot.debtEquity",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "debtEquity",
    dataSourceType: "manual_snapshot",
    expectedFormat: "number",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "performance-returns",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Return ladder",
    backendFieldKey: "stock_ohlcv_history + benchmark_ohlcv_history",
    dataSourceType: "imported_time_series",
    expectedFormat: "text",
    editableBy: "none",
    importable: true,
    requiredPriority: "critical",
    publicRouteSection: "performance",
    helpText: "Performance rows are derived from imported price history and benchmark history.",
  },
  {
    id: "performance-alpha",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Alpha / outperformance",
    backendFieldKey: "computed.performanceAlpha",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "performance",
  },
  {
    id: "performance-stock-return",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Stock return",
    backendFieldKey: "computed.stockReturn",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "performance-benchmark-return",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Benchmark return",
    backendFieldKey: "computed.benchmarkReturn",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "performance-outperformance",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Outperformance",
    backendFieldKey: "computed.outperformance",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "performance-open-at",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Open at",
    backendFieldKey: "stock_ohlcv_history.open",
    dataSourceType: "imported_time_series",
    expectedFormat: "currency",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "performance",
    helpText: "Managed by Market Data Import from daily OHLCV rows.",
  },
  {
    id: "performance-prev-close",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Prev Close",
    backendFieldKey: "stock_ohlcv_history.previous_close",
    dataSourceType: "imported_time_series",
    expectedFormat: "currency",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "performance",
    helpText: "Derived from the previous imported daily OHLCV row.",
  },
  {
    id: "performance-volumes",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Volumes",
    backendFieldKey: "stock_ohlcv_history.volume",
    dataSourceType: "imported_time_series",
    expectedFormat: "number",
    editableBy: "none",
    importable: true,
    requiredPriority: "important",
    publicRouteSection: "performance",
    helpText: "Managed by Market Data Import from daily OHLCV rows.",
  },
  {
    id: "performance-avg-price",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Avg Price",
    backendFieldKey: "computed.intradayAverage",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-lower-circuit",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Lower Circuit",
    backendFieldKey: "computed.lowerCircuit",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-upper-circuit",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "Upper Circuit",
    backendFieldKey: "computed.upperCircuit",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-3m-high",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "3 M High",
    backendFieldKey: "computed.threeMonthHigh",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-3m-low",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "3 M Low",
    backendFieldKey: "computed.threeMonthLow",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-1y-high",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "1 Yr High",
    backendFieldKey: "market_snapshot.week52High",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "week52High",
    dataSourceType: "manual_snapshot",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "performance",
  },
  {
    id: "performance-1y-low",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "1 Yr Low",
    backendFieldKey: "market_snapshot.week52Low",
    adminSectionKey: "market_snapshot",
    adminFieldKey: "week52Low",
    dataSourceType: "manual_snapshot",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "performance",
  },
  {
    id: "performance-3y-high",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "3 Yr High",
    backendFieldKey: "computed.threeYearHigh",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-3y-low",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "3 Yr Low",
    backendFieldKey: "computed.threeYearLow",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-5y-high",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "5 Yr High",
    backendFieldKey: "computed.fiveYearHigh",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-5y-low",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "5 Yr Low",
    backendFieldKey: "computed.fiveYearLow",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-1y-placement",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "1Y placement",
    backendFieldKey: "computed.oneYearPlacement",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "performance-1y-total-return",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "1Y total return",
    backendFieldKey: "computed.oneYearTotalReturn",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "performance",
  },
  {
    id: "performance-all-time-range",
    sectionId: "performance",
    sectionLabel: "Performance",
    frontendLabel: "All-time range",
    backendFieldKey: "computed.allTimeRange",
    dataSourceType: "computed",
    expectedFormat: "text",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "performance",
  },
  {
    id: "fundamentals-revenue-growth",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "Revenue growth",
    backendFieldKey: "financial_metrics.revenueGrowth",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "revenueGrowth",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-profit-growth",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "Profit growth",
    backendFieldKey: "financial_metrics.profitGrowth",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "profitGrowth",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-operating-margin",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "Operating margin",
    backendFieldKey: "financial_metrics.operatingMargin",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "operatingMargin",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-ebitda-margin",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "EBITDA margin",
    backendFieldKey: "financial_metrics.ebitdaMargin",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "ebitdaMargin",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-eps",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "EPS",
    backendFieldKey: "financial_metrics.eps",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "eps",
    dataSourceType: "source_derived",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-free-cash-flow",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "Free cash flow",
    backendFieldKey: "financial_metrics.freeCashFlow",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "freeCashFlow",
    dataSourceType: "source_derived",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-net-debt-ebitda",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "Net debt / EBITDA",
    backendFieldKey: "financial_metrics.netDebtToEbitda",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "netDebtToEbitda",
    dataSourceType: "source_derived",
    expectedFormat: "number",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "fundamentals-book-value",
    sectionId: "fundamentals",
    sectionLabel: "Fundamentals",
    frontendLabel: "Book value",
    backendFieldKey: "financial_metrics.bookValue",
    adminSectionKey: "financial_metrics",
    adminFieldKey: "bookValue",
    dataSourceType: "source_derived",
    expectedFormat: "currency",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "ownership-promoters",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "Promoters",
    backendFieldKey: "ownership_metrics.promoterHolding",
    adminSectionKey: "ownership_metrics",
    adminFieldKey: "promoterHolding",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-fiis",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "FIIs",
    backendFieldKey: "ownership_metrics.fiiHolding",
    adminSectionKey: "ownership_metrics",
    adminFieldKey: "fiiHolding",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-diis",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "DIIs",
    backendFieldKey: "ownership_metrics.diiHolding",
    adminSectionKey: "ownership_metrics",
    adminFieldKey: "diiHolding",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-public",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "Public",
    backendFieldKey: "ownership_metrics.publicHolding",
    adminSectionKey: "ownership_metrics",
    adminFieldKey: "publicHolding",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-mutual-funds",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "Mutual Funds",
    backendFieldKey: "ownership_metrics.mutualFundHolding",
    adminSectionKey: "ownership_metrics",
    adminFieldKey: "mutualFundHolding",
    dataSourceType: "source_derived",
    expectedFormat: "percent",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-top-shareholders",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "Top 5 Shareholders",
    backendFieldKey: "ownership_tables.topShareholders",
    dataSourceType: "source_derived",
    expectedFormat: "textarea",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-investor-timeline",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "Investor Details timeline",
    backendFieldKey: "ownership_tables.investorTimeline",
    dataSourceType: "source_derived",
    expectedFormat: "textarea",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "ownership",
  },
  {
    id: "ownership-mutual-fund-owners",
    sectionId: "ownership",
    sectionLabel: "Ownership",
    frontendLabel: "Mutual Funds Invested",
    backendFieldKey: "ownership_tables.mutualFundOwners",
    dataSourceType: "source_derived",
    expectedFormat: "textarea",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "ownership",
  },
  {
    id: "forecast-thesis",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Opening brief thesis",
    backendFieldKey: "frontend_fields.thesis",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "thesis",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "forecast",
  },
  {
    id: "forecast-headline-label",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Headline label",
    backendFieldKey: "frontend_fields.momentumLabel",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "momentumLabel",
    dataSourceType: "editorial_content",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "forecast",
  },
  {
    id: "forecast-research-details",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Research details",
    backendFieldKey: "frontend_fields.keyPointsText",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "keyPointsText",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "forecast",
  },
  {
    id: "forecast-analyst-target",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Analyst target",
    backendFieldKey: "computed.analystTarget",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "forecast-fair-value-gap",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Fair value gap",
    backendFieldKey: "computed.fairValueGap",
    dataSourceType: "computed",
    expectedFormat: "percent",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "forecast-next-catalyst",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Next catalyst",
    backendFieldKey: "computed.nextCatalyst",
    dataSourceType: "computed",
    expectedFormat: "date",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "forecast-rs-rank",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "RS rank",
    backendFieldKey: "computed.rsRank",
    dataSourceType: "computed",
    expectedFormat: "number",
    editableBy: "none",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "forecast-12m-avg-price",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "12M Avg Price",
    backendFieldKey: "computed.forecastAveragePrice",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "forecast",
  },
  {
    id: "forecast-low",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Low forecast",
    backendFieldKey: "computed.forecastLow",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "forecast",
  },
  {
    id: "forecast-base",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "Base forecast",
    backendFieldKey: "computed.forecastBase",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "forecast",
  },
  {
    id: "forecast-high",
    sectionId: "forecast",
    sectionLabel: "Forecast",
    frontendLabel: "High forecast",
    backendFieldKey: "computed.forecastHigh",
    dataSourceType: "computed",
    expectedFormat: "currency",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "forecast",
  },
  {
    id: "latest-news-feed",
    sectionId: "latest_news",
    sectionLabel: "Latest news",
    frontendLabel: "Matched market news feed",
    backendFieldKey: "market_news.entity_match_feed",
    dataSourceType: "source_derived",
    expectedFormat: "text",
    editableBy: "none",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "latest-news",
    helpText: "Article matching is automated from Market News and is not edited here.",
  },
  {
    id: "latest-news-readiness-note",
    sectionId: "latest_news",
    sectionLabel: "Latest news",
    frontendLabel: "News readiness note",
    backendFieldKey: "frontend_fields.newsReadinessNote",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "newsReadinessNote",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "latest-news",
  },
  {
    id: "latest-news-context-items",
    sectionId: "latest_news",
    sectionLabel: "Latest news",
    frontendLabel: "Route context items",
    backendFieldKey: "frontend_fields.newsItemsText",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "newsItemsText",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "latest-news",
  },
  {
    id: "faq-items",
    sectionId: "faq",
    sectionLabel: "FAQ",
    frontendLabel: "FAQ items",
    backendFieldKey: "frontend_fields.faqText",
    adminSectionKey: "frontend_fields",
    adminFieldKey: "faqText",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "faq",
  },
  {
    id: "seo-meta-title",
    sectionId: "seo_sharing",
    sectionLabel: "SEO / sharing",
    frontendLabel: "Meta title",
    backendFieldKey: "seo.metaTitle",
    adminSectionKey: "seo",
    adminFieldKey: "metaTitle",
    dataSourceType: "editorial_content",
    expectedFormat: "text",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "seo-meta-description",
    sectionId: "seo_sharing",
    sectionLabel: "SEO / sharing",
    frontendLabel: "Meta description",
    backendFieldKey: "seo.metaDescription",
    adminSectionKey: "seo",
    adminFieldKey: "metaDescription",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "seo-og-image",
    sectionId: "seo_sharing",
    sectionLabel: "SEO / sharing",
    frontendLabel: "OG image",
    backendFieldKey: "seo.ogImage",
    adminSectionKey: "seo",
    adminFieldKey: "ogImage",
    dataSourceType: "editorial_content",
    expectedFormat: "url",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "seo-canonical-url",
    sectionId: "seo_sharing",
    sectionLabel: "SEO / sharing",
    frontendLabel: "Canonical URL",
    backendFieldKey: "seo.canonicalUrl",
    adminSectionKey: "seo",
    adminFieldKey: "canonicalUrl",
    dataSourceType: "editorial_content",
    expectedFormat: "url",
    editableBy: "admin",
    importable: false,
    requiredPriority: "important",
    publicRouteSection: "summary",
  },
  {
    id: "seo-noindex",
    sectionId: "seo_sharing",
    sectionLabel: "SEO / sharing",
    frontendLabel: "Noindex",
    backendFieldKey: "seo.noIndex",
    adminSectionKey: "seo",
    adminFieldKey: "noIndex",
    dataSourceType: "editorial_content",
    expectedFormat: "text",
    editableBy: "admin",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
    options: yesNoOptions,
  },
  {
    id: "documents-links",
    sectionId: "documents_references",
    sectionLabel: "Documents / references",
    frontendLabel: "Document links",
    backendFieldKey: "documents_links.documentLinksText",
    adminSectionKey: "documents_links",
    adminFieldKey: "documentLinksText",
    dataSourceType: "editorial_content",
    expectedFormat: "textarea",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "documents-primary-source-url",
    sectionId: "documents_references",
    sectionLabel: "Documents / references",
    frontendLabel: "Primary source URL",
    backendFieldKey: "data_sources.sourceUrl",
    adminSectionKey: "data_sources",
    adminFieldKey: "sourceUrl",
    dataSourceType: "source_derived",
    expectedFormat: "url",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "documents-fundamentals-source-url",
    sectionId: "documents_references",
    sectionLabel: "Documents / references",
    frontendLabel: "Fundamentals source URL",
    backendFieldKey: "documents_links.fundamentalsSourceUrl",
    adminSectionKey: "documents_links",
    adminFieldKey: "fundamentalsSourceUrl",
    dataSourceType: "source_derived",
    expectedFormat: "url",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
  {
    id: "documents-shareholding-source-url",
    sectionId: "documents_references",
    sectionLabel: "Documents / references",
    frontendLabel: "Shareholding source URL",
    backendFieldKey: "documents_links.shareholdingSourceUrl",
    adminSectionKey: "documents_links",
    adminFieldKey: "shareholdingSourceUrl",
    dataSourceType: "source_derived",
    expectedFormat: "url",
    editableBy: "editor",
    importable: false,
    requiredPriority: "optional",
    publicRouteSection: "summary",
  },
];

const stockInlineEditSections: StockInlineEditSection[] = [
  {
    id: "hero_identity",
    label: "Edit hero",
    description: "Update the identity strip, comparison index, and opening stock summary while viewing the live layout.",
    entryIds: [
      "hero-company-name",
      "hero-symbol",
      "hero-sector",
      "hero-sector-index",
      "hero-summary",
    ],
  },
  {
    id: "price_snapshot",
    label: "Edit price snapshot",
    description: "Use manual snapshot fields for the hero quote and 52-week range. Daily candles remain import-managed.",
    entryIds: [
      "snapshot-current-price",
      "snapshot-day-change",
      "snapshot-as-of",
      "snapshot-market-cap",
      "range-52w-high",
      "range-52w-low",
    ],
    managedByImportNote:
      "Today open, high, low, close, and chart history are managed by Market Data Import.",
  },
  {
    id: "investor_details",
    label: "Edit investor details",
    description: "Match the investor details grid on the frontend to the exact backend fields behind those visible values.",
    entryIds: [
      "investor-pe",
      "investor-pb",
      "investor-roe",
      "investor-roce",
      "investor-dividend-yield",
      "investor-debt-equity",
    ],
  },
  {
    id: "fundamentals",
    label: "Edit fundamentals",
    description: "Update the fundamentals block in the same order that it appears on the public stock page.",
    entryIds: [
      "fundamentals-revenue-growth",
      "fundamentals-profit-growth",
      "fundamentals-operating-margin",
      "fundamentals-ebitda-margin",
      "fundamentals-eps",
      "fundamentals-free-cash-flow",
      "fundamentals-net-debt-ebitda",
      "fundamentals-book-value",
    ],
  },
  {
    id: "ownership",
    label: "Edit ownership",
    description: "Change the visible shareholding split without editing raw text blobs.",
    entryIds: [
      "ownership-promoters",
      "ownership-fiis",
      "ownership-diis",
      "ownership-public",
    ],
  },
  {
    id: "forecast",
    label: "Edit forecast",
    description: "Adjust the editorial forecast copy and research notes while the chart itself stays durable-data driven.",
    entryIds: [
      "forecast-thesis",
      "forecast-headline-label",
      "forecast-research-details",
    ],
    managedByImportNote:
      "Forecast chart geometry stays computed from chart history and cannot be edited manually here.",
  },
  {
    id: "seo_content",
    label: "Edit SEO / content",
    description: "Handle SEO, FAQ, latest-news notes, and traceable supporting links from the public route itself.",
    entryIds: [
      "faq-items",
      "latest-news-readiness-note",
      "latest-news-context-items",
      "seo-meta-title",
      "seo-meta-description",
      "seo-og-image",
      "seo-canonical-url",
      "seo-noindex",
      "documents-links",
      "documents-primary-source-url",
      "documents-fundamentals-source-url",
      "documents-shareholding-source-url",
    ],
  },
];

function readEditorRecordValue(
  record: AdminEditorRecord,
  adminSectionKey?: string | null,
  adminFieldKey?: string | null,
) {
  if (!adminSectionKey || !adminFieldKey) {
    return "";
  }

  const section = record.sections.find((item) => item.definition.key === adminSectionKey);
  if (!section) {
    return "";
  }

  return (
    section.effectiveValues[adminFieldKey] ??
    section.manualValues[adminFieldKey] ??
    section.sourceValues[adminFieldKey] ??
    ""
  );
}

function isMissingValue(value: string) {
  const normalized = value.trim().toLowerCase();
  return !normalized || normalized === "unavailable" || normalized === "awaiting extended history";
}

function buildStatusLabel(entry: StockFieldRegistryEntry, currentValue: string) {
  if (entry.dataSourceType === "imported_time_series") {
    return "Managed by Market Data Import";
  }

  if (entry.dataSourceType === "computed") {
    return "Computed on the frontend";
  }

  if (isMissingValue(currentValue)) {
    return "Needs data";
  }

  if (entry.dataSourceType === "source_derived") {
    return "Source-backed / overrideable";
  }

  if (entry.dataSourceType === "manual_snapshot") {
    return "Manual snapshot";
  }

  return "Editorial field";
}

export function getStockFieldRegistry() {
  return stockFieldRegistry;
}

export function getStockFieldRegistryBySection(sectionId?: StockFieldSectionId) {
  if (!sectionId) {
    return stockFieldRegistry;
  }

  return stockFieldRegistry.filter((entry) => entry.sectionId === sectionId);
}

export function getStockInlineEditSections() {
  return stockInlineEditSections;
}

export function buildStockFieldMapRows(record: AdminEditorRecord) {
  return stockFieldRegistry.map((entry) => {
    const currentValue = readEditorRecordValue(
      record,
      entry.adminSectionKey ?? null,
      entry.adminFieldKey ?? null,
    );

    return {
      ...entry,
      currentValue,
      missing:
        entry.dataSourceType === "imported_time_series" || entry.dataSourceType === "computed"
          ? false
          : isMissingValue(currentValue),
      statusLabel: buildStatusLabel(entry, currentValue),
    } satisfies StockFieldMapRow;
  });
}

export function getStockInlineEditRows(
  record: AdminEditorRecord,
  sectionId: StockInlineEditSectionId,
  role: StockFieldEditableBy,
) {
  const section = stockInlineEditSections.find((item) => item.id === sectionId);
  if (!section) {
    return [];
  }

  const rowMap = new Map(buildStockFieldMapRows(record).map((row) => [row.id, row]));
  return section.entryIds
    .map((id) => rowMap.get(id))
    .filter((row): row is StockFieldMapRow => Boolean(row))
    .filter((row) => row.editableBy === "none" || row.editableBy === role || role === "admin");
}
