export type ToolAccess = "Free" | "Signup recommended" | "Subscriber upgrade later";

export type ToolItem = {
  slug: string;
  title: string;
  category: string;
  access: ToolAccess;
  summary: string;
  outcome: string;
  inputLabel: string;
  samplePrompt: string;
};

export const tools: ToolItem[] = [
  {
    slug: "position-size-calculator",
    title: "Position Size Calculator",
    category: "Trading Utility",
    access: "Free",
    summary: "Helps users estimate trade size based on capital, risk per trade, and stop-loss distance.",
    outcome: "Encourages disciplined risk management and repeat usage.",
    inputLabel: "Capital, risk %, entry, stop-loss",
    samplePrompt: "I have ₹2,00,000 capital, want to risk 1%, entry 945, stop 922.",
  },
  {
    slug: "ipo-lot-calculator",
    title: "IPO Lot Calculator",
    category: "IPO Utility",
    access: "Free",
    summary: "Shows application amount, lots, and capital requirement for mainboard and SME IPOs.",
    outcome: "Useful during IPO season and naturally connects with IPO pages.",
    inputLabel: "Lot size, price band, number of lots",
    samplePrompt: "Lot size 26, price band 560, applying for 3 lots.",
  },
  {
    slug: "sip-goal-planner",
    title: "SIP Goal Planner",
    category: "Wealth Utility",
    access: "Signup recommended",
    summary: "Interactive SIP calculator with step-up assumptions, inflation framing, corpus visuals, and downloadable planning output.",
    outcome: "Turns long-term investing into a repeat-use planning workflow instead of a one-line estimate.",
    inputLabel: "Monthly SIP, years, return, step-up %, inflation",
    samplePrompt: "Plan a ₹10,000 monthly SIP for 20 years with 12% return and 10% yearly step-up.",
  },
  {
    slug: "breakout-checklist",
    title: "Breakout Checklist",
    category: "Trading Utility",
    access: "Signup recommended",
    summary: "Guides users through structured breakout checks like volume, trend, stop, and risk alignment.",
    outcome: "Pairs well with charts and future indicator workflows.",
    inputLabel: "Stock, breakout level, volume note",
    samplePrompt: "Tata Motors above 960 with strong volume, what should I check?",
  },
  {
    slug: "portfolio-overlap-checker",
    title: "Portfolio Overlap Checker",
    category: "Portfolio Utility",
    access: "Subscriber upgrade later",
    summary: "Checks concentration and overlap across stocks, mutual funds, or imported holdings.",
    outcome: "Creates a strong bridge into portfolio tracking and saved-account workflows.",
    inputLabel: "Holdings list or imported portfolio",
    samplePrompt: "Check overlap between my large-cap fund and direct stock holdings.",
  },
  {
    slug: "retirement-corpus-planner",
    title: "Retirement Corpus Planner",
    category: "Wealth Utility",
    access: "Signup recommended",
    summary: "Helps users estimate the target corpus and monthly investment needed for retirement goals.",
    outcome: "Strong evergreen tool that supports wealth-product discovery and future saved planning journeys.",
    inputLabel: "Current age, retirement age, expense target, return assumptions",
    samplePrompt: "I am 32, want to retire at 55, and need ₹1.5 lakh monthly in today’s terms.",
  },
  {
    slug: "goal-allocation-checker",
    title: "Goal Allocation Checker",
    category: "Wealth Utility",
    access: "Signup recommended",
    summary: "Checks whether an investor’s current split across equity, debt, and alternatives matches a stated goal and time horizon.",
    outcome: "Natural bridge into mutual funds, ETFs, PMS, and AIF pages.",
    inputLabel: "Goal horizon, current allocation, target amount",
    samplePrompt: "My goal is 7 years away and I am 80% equity, 10% debt, 10% cash. Is that sensible?",
  },
  {
    slug: "swp-withdrawal-planner",
    title: "SWP Withdrawal Planner",
    category: "Wealth Utility",
    access: "Signup recommended",
    summary: "Interactive withdrawal planner for post-tax income, asset-mix returns, step-up assumptions, and corpus longevity.",
    outcome: "Adds a genuinely useful retirement-income workflow instead of only a static post-retirement note.",
    inputLabel: "Corpus, monthly withdrawal, mix, returns, tax slab",
    samplePrompt: "Can a ₹2 crore corpus support ₹80,000 monthly withdrawals with a blended equity-debt mix?",
  },
  {
    slug: "asset-location-checklist",
    title: "Asset Location Checklist",
    category: "Portfolio Utility",
    access: "Free",
    summary: "Helps users review where direct stocks, funds, ETFs, and alternatives sit inside the broader portfolio and where concentration may be building.",
    outcome: "Supports recurring portfolio check-ins and better wealth-product recommendations later.",
    inputLabel: "Current holdings mix across products",
    samplePrompt: "I hold direct stocks, two mutual funds, one ETF, and one PMS allocation. What should I review?",
  },
  {
    slug: "fire-retirement-calculator",
    title: "F.I.R.E. Retirement Calculator",
    category: "Wealth Utility",
    access: "Signup recommended",
    summary: "Detailed financial-independence planner with milestone tracking, corpus scenarios, and retirement sustainability checks.",
    outcome: "Gives the tool hub a stronger wealth-planning anchor beyond SIP and SWP workflows.",
    inputLabel: "Age, expenses, corpus, savings rate, return and inflation assumptions",
    samplePrompt: "Show my FIRE number if I want to retire at 50 with ₹1 lakh monthly expenses in today’s terms.",
  },
  {
    slug: "gold-price-tracker",
    title: "Gold Price Tracker",
    category: "Commodity Utility",
    access: "Free",
    summary: "Live landed gold-rate tracker with purity breakdowns, charts, and investment-cost calculations for Indian buyers.",
    outcome: "Adds real-time market utility that connects tools with broader market discovery.",
    inputLabel: "Gold purity, grams, making charges",
    samplePrompt: "Show today’s 24K and 22K gold rates and estimate the cost of buying 10 grams.",
  },
  {
    slug: "silver-price-tracker",
    title: "Silver Price Tracker",
    category: "Commodity Utility",
    access: "Free",
    summary: "Live silver tracker with 999, 925, and 900 purity rates, price history, and purchase-cost estimates.",
    outcome: "Extends the market layer into commodities with a useful daily-check tool.",
    inputLabel: "Silver purity, grams, making charges",
    samplePrompt: "Show today’s 999 silver rate and calculate the total for a 100-gram purchase.",
  },
  {
    slug: "pdf-compressor",
    title: "PDF Compressor",
    category: "File Utility",
    access: "Free",
    summary: "Browser-based PDF compressor that reduces file size without sending documents to a separate upload workflow.",
    outcome: "Brings broader utility traffic into the platform while staying immediately usable.",
    inputLabel: "One or more PDF files",
    samplePrompt: "Compress three PDF files and keep the output smaller than the original where possible.",
  },
  {
    slug: "pdf-to-word-converter",
    title: "PDF to Word Converter",
    category: "File Utility",
    access: "Free",
    summary: "Converts PDF files into Word-ready output through a browser-side utility flow.",
    outcome: "Adds another practical, shareable tool that broadens top-of-funnel traffic.",
    inputLabel: "PDF file",
    samplePrompt: "Convert this PDF into a Word document I can edit.",
  },
  {
    slug: "pdf-splitter",
    title: "PDF Splitter",
    category: "File Utility",
    access: "Free",
    summary: "Splits a PDF into separate page ranges directly in the browser.",
    outcome: "Makes the tools hub feel deeper and more complete for day-to-day utility use.",
    inputLabel: "PDF file and page ranges",
    samplePrompt: "Split this 20-page PDF into pages 1-5 and 6-20.",
  },
  {
    slug: "pdf-merger",
    title: "PDF Merger",
    category: "File Utility",
    access: "Free",
    summary: "Merges multiple PDFs into one combined file without leaving the tool flow.",
    outcome: "Adds a simple high-frequency utility that can attract repeat visits beyond finance-only use cases.",
    inputLabel: "Two or more PDF files",
    samplePrompt: "Merge these quarterly reports into one PDF.",
  },
  {
    slug: "pdf-unlocker",
    title: "PDF Unlocker",
    category: "File Utility",
    access: "Free",
    summary: "Unlocks supported PDF files for easier reuse and viewing inside a browser-side workflow.",
    outcome: "Completes the PDF utility cluster with another practical everyday tool.",
    inputLabel: "Protected PDF file",
    samplePrompt: "Unlock this PDF so I can work with it more freely.",
  },
  {
    slug: "pdf-protector",
    title: "PDF Protector",
    category: "File Utility",
    access: "Free",
    summary: "Protects PDFs with password-based access controls directly from the browser.",
    outcome: "Rounds out the PDF stack with a privacy and sharing utility.",
    inputLabel: "PDF file and password",
    samplePrompt: "Protect this PDF with a password before I share it.",
  },
  {
    slug: "instagram-reel-downloader",
    title: "Instagram Reel Downloader",
    category: "Social Utility",
    access: "Free",
    summary: "Utility flow for fetching downloadable reel assets from a shared Instagram reel link.",
    outcome: "Adds one more high-intent general-use utility to the tool hub.",
    inputLabel: "Instagram reel URL",
    samplePrompt: "Download this Instagram reel from its shared link.",
  },
];

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug) ?? null;
}
